typography_spectrum: 0.816550764720887
color:
  brandStrength: 0.30559876607730985
  lightness: 0.9721079661976546
  saturation: 0.17207641154527664
  rhythmicContrast: 0.7501984774135053
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
layout_spectrum: 0.09040387207642198
name: Resolhuman
navigation:
  - name: Qui sommes nous
    url: Qui sommes nous
    type: external
  - name: Thématiques
    url: Nos Thématiques
    type: external
  - name: Interventions
    url: Nos interventions
    type: external
title: Resolhuman
description: Transformation des entreprises et des organisations
